/* 화면 문구 사전 — 부서 문체 규칙(style-spec.md) 적용.
   개조식(-함/-임/-음), 한 문장 한 정보, 줄표 없음, 가운뎃점 ㆍ, 순화어(스냅샷→보관본, 백업→보관본). 버튼 = 동사 + 범위 + 수량.
   scripts/style_check.py 로 검사한다(연도 없는 표 안 날짜는 기간 줄이 연도를 정하므로 예외). */
export const C = {
  app: "직거래 일정관리",
  layer1: { title: (n: number, need: number) => need ? `오늘 ${n}건 중 ${need}건 확인 필요.` : n ? `오늘 ${n}건. 확인 필요 없음.` : "오늘 일정 없음.",
    secNeeds: (n: number) => `확인ㆍ연락 필요 ${n}`, secRest: (n: number) => `오늘 나머지 ${n}`, secNext: "다음 일정",
    secConflict: (n: number) => `날짜와 무관한 충돌 ${n}. 오늘 건수에 포함하지 않음.`, secVendors: (n: number) => `오늘 참가 업체 ${n}곳`,
    emptyNext: "다음 3건을 대신 보임.", openCalendar: "캘린더 열기", quickAdd: "일정 추가",
    check: "확인 처리", open: "열기", checkTip: "확인 처리 (Space). 바로 저장하고 8초 안에 되돌릴 수 있음.", openTip: "인스펙터에서 열기 (Enter)" },
  widget: { comes: (n: number) => `${n}곳 나옴`, noReply: (n: number) => `회신 없는 곳 ${n}`, allReplied: "전부 회신 받았음", none: "예정된 운영일 없음",
    clickThrough: "클릭 통과 켜짐. 트레이에서 끌 수 있음", edit: "위치 조정", editTip: "방향키 1px ㆍ Shift+방향키 8px ㆍ Enter 저장 ㆍ Esc 취소" },
  views: { month: "월간", week: "주간", matrix: "기간표", today: "오늘", prev: "이전 달", next: "다음 달", search: "검색", cmd: "명령",
    inspectorOpen: "인스펙터 펼치기", inspectorClose: "인스펙터 접기", widgetShow: "바탕화면 위젯 보기", widgetHide: "위젯 감춤" },
  matrix: { vendorCol: "업  체", days: "일수", memo: "비  고", legend: "■ 참가 ㆍ □ 회신 없음 ㆍ ─ 그날만 빠짐. 칸을 누르면 그날만 바뀌고 나오는 요일은 그대로 둠.",
    export: "표 내려받기", exported: "표를 CSV로 내려받았음. 결재 문서에 붙일 수 있음.", empty: "이 행사에 등록된 업체가 없음. 업체를 등록하면 여기에 운영표가 생김." },
  month: { toMatrix: "이 주를 기간표에서 보기", hint: (max: number[]) => `주 최대 항목 ${max.join(" / ")}. 이름은 숨기지 않고 행 높이를 늘림.` },
  status: { confirmed: "참가", needs: "회신 없음", changed: "그날만 나옴", cancelled: "그날만 빠짐", taskNeeds: "확인 필요", taskOk: "확정", done: "처리함" },
  dialog: {
    quickAdd: { title: "일정 추가", sub: "제목과 일시만으로 저장함. 업체ㆍ행사 연결은 선택.", titleLabel: "제목", dateLabel: "날짜", timeLabel: "시각 (빈 값 = 종일)", linkLabel: "연결 (선택)",
      save: "저장", saveKeep: "저장하고 계속", cancel: "취소", saved: (t: string) => `저장함. ${t}`, needTitle: "제목을 적을 것", ime: "한글 조합 중 Enter는 무시함. 조합이 끝난 뒤 저장함." },
    vendor: { title: "업체 등록", sec1: "기본 정보", sec2: "행사 선택", sec3: "기간", sec4: "나오는 요일", sec5: "실제 참가일", name: "업체명", contact: "담당자", phone: "연락처", products: "품목 (쉼표로 구분)",
      event: "행사", start: "시작", end: "끝", save: "업체 저장", cancel: "취소", dup: (n: string) => `같은 이름 ${n} 1곳 있음. 그대로 등록할 수 있음.`, needWeekday: "나오는 요일을 한 개 이상 고를 것", needName: "업체명을 적을 것",
      preview: (wd: string, n: number, first: string, last: string) => `${wd} 참가ㆍ${n}일ㆍ첫 ${first}ㆍ마지막 ${last}`, previewNone: "참가일 없음", saved: (n: string) => `업체 등록함. ${n}` },
    planEdit: { title: (v: string, e: string) => `계획 편집 ㆍ ${v} × ${e}`, sub: (p: string, n: number, wd: string) => `${p}, ${n}일. 현재 ${wd}.`,
      weekdays: "나오는 요일", start: "시작", end: "끝", add: (n: number) => `늘어나는 날 ${n}일`, rem: (n: number) => `빠지는 날 ${n}일`,
      conflicts: (n: number) => `기존 그날만 변경 ${n}건이 의미를 잃음. 하나씩 정하기 전에는 저장할 수 없음.`, keep: "유지", drop: "삭제",
      save: (a: number, r: number) => `계획 저장 ㆍ +${a}일 −${r}일`, cancel: "취소", needWeekday: "나오는 요일을 한 개 이상 고를 것", nochange: "바뀐 것이 없음",
      saved: (v: string, a: number, r: number) => `${v} 계획 저장함. +${a}일 −${r}일.` },
    dayEx: { sub: (v: string) => `${v}. 다른 날짜에는 영향 없음.`, planned: (s: string) => `계획: ${s}`, come: "이 날만 나옴", skip: "이 날만 빠짐", reason: "이유ㆍ메모 (선택)",
      effectSame: "계획과 같음. 저장해도 달라지는 것이 없음.", effect: (s: string) => `이 날짜만 ${s}으로 표시함. 계획은 바뀌지 않음.`, overwrite: (prev: string) => `이미 그날만 변경이 있음(${prev}). 덮어씀.`,
      toPlan: "반복 요일을 바꾸려면 계획 편집으로", save: (d: string) => `${d} 하루만 저장`, cancel: "취소", saved: (d: string, v: string, s: string) => `${d} ${v} ${s}으로 표시함.`, cleared: (d: string, v: string) => `${d} ${v} 그날만 변경을 지움.` },
    restore: { title: "보관본에서 복원", sub: "고르기만 해서는 아무것도 덮어쓰지 않음.", list: "보관본", preview: "바뀌는 양", snapshot: "복원 전에 지금 상태를 보관본으로 남김.",
      save: "지금 상태를 보관하고 복원", cancel: "취소", loading: "바뀌는 양을 계산하는 중", restored: (l: string) => `복원함. ${l}`, undo: "복원 취소 (보관본으로 되돌리기)", bar: (l: string) => `복원함 ㆍ ${l}` },
    escDirty: "고친 내용을 버릴까요?", keepEditing: "계속 편집", discard: "버리기",
  },
  inspector: { pick: "날짜ㆍ업체ㆍ행사를 고르면 여기에 보임.", basic: "기본 정보", contact: "담당자", phone: "연락처", phoneTip: "기본 가림. 누르면 원문", products: "품목",
    plan: (e: string) => `참가계획 ㆍ ${e}`, planEdit: "계획 편집", planEditTip: "전체 일정 변경의 유일한 진입점. 날짜 셀 메뉴에는 없음.", days: (n: number) => `참가일 ${n}일`, dayEdit: "이 날짜만 수정",
    conflicts: "충돌", none: "없음", orphan: (d: string, p: string) => `계획 밖 예외 ㆍ ${d}는 계획 기간(${p}) 밖임. 예외를 지우거나 기간을 늘릴 것.`,
    overlap: (a: string, b: string) => `같은 행사에 기간이 겹치는 계획 2건 ㆍ ${a} / ${b}`, invalid: "나오는 요일이 0개라 참가일을 계산할 수 없음. 요일을 한 개 이상 고를 것.",
    attach: (n: number) => `첨부 ${n}개`, missing: "파일 없음 ㆍ 위치 찾기", history: (n: number) => `변경 이력 ${n}건`, revert: "이 값으로 되돌리기", actor: (a: string) => `기록자 ${a}`,
    dup: (_m: string) => `같은 이름 1곳 있음. 담당자ㆍ연락처로 구분할 것.`, event: { period: "기  간", place: "장  소", vendors: (n: number) => `참가업체 ${n}곳`, days: "운영일" },
    task: { when: "일  시", memo: "메  모", linked: "연  결" } },
  toast: { undone: "되돌렸음.", checked: (t: string) => `확인 처리함. ${t}`, cellSkip: (d: string, v: string) => `${d} ${v} 그날만 빠짐으로 표시함. 나오는 요일은 바뀌지 않음.`,
    cellCome: (d: string, v: string) => `${d} ${v} 그날만 나옴으로 표시함. 나오는 요일은 바뀌지 않음.`, cellClear: (d: string, v: string) => `${d} ${v} 그날만 변경을 지움.`,
    reply: (v: string, ok: boolean) => ok ? `${v} 회신 받음으로 표시함.` : `${v} 회신 없음으로 되돌림.` },
  error: { db: "자료를 열 수 없음. 파일이 다른 프로그램에서 사용 중임. 다시 시도하거나 프로그램을 다시 열 것.", retry: "다시 시도" },
} as const;
