(async function(){
  const C=window.WorkCore;let state=await C.initStorage();let currentMonth=new Date(2026,7,1);let selectedRecord=null;let selectedProjectId=null;let templateTab='vendor';let selectedVendorTemplateId=null;let selectedWorkTemplateId=null;let projectStepsDraft=[];
  const $=id=>document.getElementById(id);const q=(s,r=document)=>r.querySelector(s);const qa=(s,r=document)=>[...r.querySelectorAll(s)];
  function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1700)}
  function show(id){$(id).classList.add('show')}function hide(id){$(id).classList.remove('show')}
  async function persist(msg){await C.saveState(state);render();if(msg)toast(msg)}
  function render(){renderHorizon();renderDue();renderCalendar();fillSelects();renderTemplatePanes();}
  function renderHorizon(){const s=state.settings;$('horizonSelect').value=s.horizon;$('horizonCustom').value=s.customHorizon;$('horizonCustom').classList.toggle('hidden',s.horizon!=='custom')}
  function renderDue(){const cards=C.dueCards(state),host=$('dueList');if(!cards.length){const blank=!state.projects.length&&!state.manualEvents.length;host.innerHTML=`<div class="empty">${blank?'등록된 업무가 없습니다.<br>위쪽 <b>업무 추가</b>로 시작하거나,<br>설정에서 예시 데이터를 불러오세요.':'설정한 기준 안에 예정된 일정이 없습니다.'}</div>`;return}host.innerHTML=cards.map(r=>{const v=C.vendor(state,r.vendorId),p=C.project(state,r.projectId);return `<button class="due-card ${C.ddayClass(r.date)}" data-due-kind="${r.kind}" data-due-id="${r.id}"><span><span class="due-vendor">${C.esc(v?.name||'업체 미지정')}</span><span class="due-task">${C.esc(r.name)}</span><span class="due-sub">${C.pretty(r.date)}${p?` · ${C.esc(p.name)}`:''}</span>${r.extra?`<span class="due-extra">이후 일정 ${r.extra}건</span>`:''}</span><span class="due-dday">${C.ddayLabel(r.date)}</span></button>`}).join('');qa('[data-due-id]',host).forEach(b=>b.addEventListener('click',()=>openRecord(b.dataset.dueKind,b.dataset.dueId)))}
  function allEventRecords(){return C.eventRecords(state)}
  function renderCalendar(){const y=currentMonth.getFullYear(),m=currentMonth.getMonth();$('monthTitle').textContent=`${y}년 ${m+1}월`;$('monthGrid').innerHTML='';const first=new Date(y,m,1),before=first.getDay(),days=new Date(y,m+1,0).getDate(),cells=Math.ceil((before+days)/7)*7,events=allEventRecords();for(let i=0;i<cells;i++){const d=new Date(y,m,1-before+i),ds=C.iso(d),inMonth=d.getMonth()===m,isToday=ds===C.todayISO(),rows=events.filter(e=>e.date===ds).sort((a,b)=>Number(a.completed)-Number(b.completed));const cell=document.createElement('div');cell.className=`day ${inMonth?'':'out'} ${[0,6].includes(d.getDay())?'weekend':''} ${isToday?'today':''}`;cell.dataset.date=ds;cell.innerHTML=`<div class="day-head"><span class="day-num">${d.getDate()}</span>${isToday?'<span class="today-label">TODAY</span>':''}</div><div class="events">${rows.map(r=>{const v=C.vendor(state,r.vendorId);return `<button class="event ${r.completed?'done':''} ${r.kind==='manual'?'manual':''} ${!r.completed?C.ddayClass(r.date):''}" data-event-kind="${r.kind}" data-event-id="${r.id}" title="${C.esc(v?.name||'')} · ${C.esc(r.name)}">${r.completed?'✓ ':''}${C.esc(v?.name||'업체')} · ${C.esc(r.name)}</button>`}).join('')}</div>${inMonth?'<span class="add-hint">+ 일정</span>':''}`;if(inMonth)cell.addEventListener('click',e=>{if(e.target.closest('[data-event-id]'))return;openSchedule(ds)});$('monthGrid').appendChild(cell)}qa('[data-event-id]',$('monthGrid')).forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openRecord(b.dataset.eventKind,b.dataset.eventId)}))}
  function fillSelects(){const vendorOpts=state.vendorTemplates.map(v=>`<option value="${v.id}">${C.esc(v.name)}</option>`).join('');$('sVendor').innerHTML=vendorOpts;$('wVendor').innerHTML=vendorOpts;$('wTemplate').innerHTML=state.workTemplates.map(t=>`<option value="${t.id}">${C.esc(t.name)}</option>`).join('');updateProjectSelect()}
  function updateProjectSelect(){const vid=$('sVendor').value;const rows=state.projects.filter(p=>p.vendorId===vid);$('sProject').innerHTML='<option value="">일반 일정</option>'+rows.map(p=>`<option value="${p.id}">${C.esc(p.name)}</option>`).join('')}
  function openSchedule(date=C.todayISO()){selectedRecord=null;$('scheduleTitle').textContent='일정 추가';$('sDate').value=date;fillSelects();$('sName').value='';$('sMemo').value='';show('scheduleModal');setTimeout(()=>$('sName').focus(),0)}
  async function saveSchedule(){const date=$('sDate').value,vendorId=$('sVendor').value,name=$('sName').value.trim();if(!date||!vendorId||!name){toast('날짜, 업체, 일정명을 확인하세요.');return}state.manualEvents.push({id:C.uid('m'),vendorId,projectId:$('sProject').value||null,date,name,memo:$('sMemo').value.trim(),completed:false,completedAt:null,logs:[],attachments:[]});hide('scheduleModal');await persist('일정을 추가했습니다.')}
  function openWork(){fillSelects();$('wProject').value='';$('wFirstDate').value=C.todayISO();$('wMemo').value='';show('workModal')}
  async function saveWork(){const vendorId=$('wVendor').value,template=state.workTemplates.find(t=>t.id===$('wTemplate').value),name=$('wProject').value.trim(),date=$('wFirstDate').value;if(!vendorId||!template||!name||!date){toast('업체, 템플릿, 업무명, 첫 날짜를 확인하세요.');return}state.projects.push(C.projectFromTemplate(template,vendorId,name,date,$('wMemo').value.trim()));hide('workModal');await persist('업무를 등록했습니다.')}
  function findRecord(kind,id){return allEventRecords().find(r=>r.kind===kind&&r.id===id)}
  function recordEntity(record){if(!record)return null;if(record.kind==='manual')return state.manualEvents.find(x=>x.id===record.id)||null;const p=C.project(state,record.projectId);return p?.steps?.find(x=>x.id===record.id)||null}
  function stepStatus(p,s){const current=C.currentStep(p);if(s.completed)return{key:'done',label:`완료${s.completedAt?` · ${C.pretty(s.completedAt)}`:''}`};if(current?.id===s.id)return{key:'current',label:`현재${s.dueDate?` · ${C.pretty(s.dueDate)}`:''}`};return{key:'future',label:s.dueDate?`예정 · ${C.pretty(s.dueDate)}`:'예정 · 날짜 미정'}}
  function openRecord(kind,id){selectedRecord=findRecord(kind,id);if(!selectedRecord)return;const v=C.vendor(state,selectedRecord.vendorId),p=C.project(state,selectedRecord.projectId),entity=recordEntity(selectedRecord);if(entity){entity.logs=Array.isArray(entity.logs)?entity.logs:[];entity.attachments=Array.isArray(entity.attachments)?entity.attachments:[]}
    $('detailTitle').textContent='일정 상세';$('deleteEventBtn').classList.toggle('hidden',kind!=='manual');$('completeBtn').classList.toggle('hidden',selectedRecord.completed);$('changeDateBtn').classList.toggle('hidden',selectedRecord.completed);$('reopenBtn').classList.toggle('hidden',!selectedRecord.completed);const steps=p?.steps||[];
    const logs=(entity?.logs||[]).slice().sort((a,b)=>String(b.time).localeCompare(String(a.time))),files=entity?.attachments||[];
    $('detailBody').innerHTML=`<div class="detail-hero"><div><div class="detail-vendor">${C.esc(v?.name||'업체')}</div><div class="detail-project">${C.esc(p?.name||'일반 일정')}</div></div><div class="detail-dday ${selectedRecord.completed?'done':C.ddayClass(selectedRecord.date)}">${selectedRecord.completed?'완료':C.ddayLabel(selectedRecord.date)}</div></div>
    <div class="current-box"><div class="current-label">${selectedRecord.kind==='manual'?'일정':'선택 절차'}</div><div class="current-title">${C.esc(selectedRecord.name)}</div><div class="current-date">${C.pretty(selectedRecord.date)}${selectedRecord.memo?` · ${C.esc(selectedRecord.memo)}`:''}</div></div>
    <div class="info-row"><div class="info"><span>담당자</span><b>${C.esc(v?.person||'-')}</b></div><div class="info"><span>연락처</span><b>${C.esc(v?.contact||'-')}</b></div></div>
    <section class="worklog-section"><div class="section-headline"><div><b>업무 내용 기록</b><span>진행 경과, 통화·협의 내용, 전달사항을 계속 남길 수 있습니다.</span></div></div><div class="log-compose"><textarea id="workLogText" placeholder="예: 업체 담당자와 통화. 평가서 보완본을 8/14 오전까지 제출하기로 함."></textarea><button class="btn primary" id="addWorkLogBtn">기록 추가</button></div><div class="worklog-list">${logs.length?logs.map(l=>`<div class="worklog-item"><div class="worklog-time">${new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(l.time))}</div><div class="worklog-text">${C.esc(l.text)}</div><button class="tiny-link danger" data-delete-log="${l.id}">삭제</button></div>`).join(''):'<div class="section-empty">아직 기록이 없습니다.</div>'}</div></section>
    <section class="attachment-section"><div class="section-headline"><div><b>첨부파일</b><span>이 일정과 관련된 문서·사진을 로컬에 보관합니다.</span></div><label class="btn file-btn" for="detailFiles">+ 파일 첨부</label><input id="detailFiles" type="file" multiple hidden></div><div class="attachment-list">${files.length?files.map(f=>`<div class="attachment-item"><span class="file-icon">↳</span><span class="attachment-main"><b>${C.esc(f.name)}</b><small>${C.formatBytes(f.size)}</small></span><button class="tiny-link" data-download-file="${f.id}">열기/저장</button><button class="tiny-link danger" data-delete-file="${f.id}">삭제</button></div>`).join(''):'<div class="section-empty">첨부된 파일이 없습니다.</div>'}</div><div class="attachment-note">첨부파일은 이 PC/브라우저의 로컬 저장소에 보관됩니다. 다른 PC로 옮길 때는 파일 백업 기능을 별도로 추가하는 것이 안전합니다.</div></section>
    ${p?`<div class="steps"><div class="steps-head"><div><div class="steps-title">전체 업무 절차</div><div class="steps-sub">완료된 단계와 아직 오지 않은 단계까지 모두 표시합니다.</div></div><button class="link" id="editProjectSteps">절차 편집</button></div>${steps.map((s,i)=>{const st=stepStatus(p,s);return `<div class="step ${st.key}"><span class="step-mark">${s.completed?'✓':C.currentStep(p)?.id===s.id?'●':i+1}</span><span class="step-name">${C.esc(s.name)}</span><span class="step-status ${st.key}">${C.esc(st.label)}</span></div>`}).join('')}</div>`:''}`;
    show('detailModal');q('#editProjectSteps')?.addEventListener('click',()=>{hide('detailModal');openProjectSteps(p.id)});q('#addWorkLogBtn')?.addEventListener('click',addWorkLog);q('#workLogText')?.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();addWorkLog()}});q('#detailFiles')?.addEventListener('change',addAttachments);qa('[data-delete-log]',$('detailBody')).forEach(b=>b.addEventListener('click',()=>deleteWorkLog(b.dataset.deleteLog)));qa('[data-download-file]',$('detailBody')).forEach(b=>b.addEventListener('click',()=>downloadAttachment(b.dataset.downloadFile)));qa('[data-delete-file]',$('detailBody')).forEach(b=>b.addEventListener('click',()=>deleteAttachment(b.dataset.deleteFile)))
  }
  async function refreshDetail(msg){const k=selectedRecord?.kind,id=selectedRecord?.id;await C.saveState(state);render();if(k&&id)openRecord(k,id);if(msg)toast(msg)}
  async function addWorkLog(){const entity=recordEntity(selectedRecord),text=q('#workLogText')?.value.trim();if(!entity||!text)return;entity.logs=Array.isArray(entity.logs)?entity.logs:[];entity.logs.push({id:C.uid('log'),time:new Date().toISOString(),text});await refreshDetail('업무 내용을 기록했습니다.')}
  async function deleteWorkLog(id){const entity=recordEntity(selectedRecord);if(!entity)return;entity.logs=(entity.logs||[]).filter(x=>x.id!==id);await refreshDetail('기록을 삭제했습니다.')}
  async function addAttachments(e){const entity=recordEntity(selectedRecord),files=[...(e.target.files||[])];if(!entity||!files.length)return;entity.attachments=Array.isArray(entity.attachments)?entity.attachments:[];let saved=0;for(const file of files){if(file.size>50*1024*1024){toast(`${file.name}: 50MB 이하 파일만 첨부할 수 있습니다.`);continue}try{const meta=await C.putAttachment(file);entity.attachments.push(meta);saved++}catch(err){console.warn(err);toast('파일 저장을 지원하지 않는 환경입니다.')}}if(saved)await refreshDetail(`${saved}개 파일을 첨부했습니다.`)}
  async function downloadAttachment(id){try{const row=await C.getAttachment(id);if(!row?.blob){toast('파일 데이터를 찾을 수 없습니다.');return}const url=URL.createObjectURL(row.blob),a=document.createElement('a');a.href=url;a.download=row.name||'attachment';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){console.warn(e);toast('파일을 열지 못했습니다.')}}
  async function deleteAttachment(id){const entity=recordEntity(selectedRecord);if(!entity)return;if(!confirm('이 첨부파일을 삭제할까요?'))return;entity.attachments=(entity.attachments||[]).filter(x=>x.id!==id);await C.removeAttachment(id);await refreshDetail('첨부파일을 삭제했습니다.')}
  async function completeSelected(){if(!selectedRecord)return;const next=C.completeEvent(state,selectedRecord,C.todayISO());hide('detailModal');await persist(next?`완료 · 다음 일정 ${next.name} ${C.pretty(next.dueDate)}`:'완료 처리했습니다.')}
  // 날짜 변경은 네이티브 prompt() 대신 앱 안의 date 입력으로 받는다.
  function openDateModal(){if(!selectedRecord||selectedRecord.completed)return;$('dNewDate').value=selectedRecord.date;$('dateModalNote').textContent=`${C.esc(selectedRecord.name)} · 현재 ${C.pretty(selectedRecord.date)}`;show('dateModal');setTimeout(()=>$('dNewDate').focus(),0)}
  async function saveSelectedDate(){const next=$('dNewDate').value;if(!selectedRecord||!next){toast('날짜를 선택하세요.');return}
    if(selectedRecord.kind==='manual'){const m=state.manualEvents.find(x=>x.id===selectedRecord.id);if(m)m.date=next}
    else{const p=C.project(state,selectedRecord.projectId),s=p?.steps.find(x=>x.id===selectedRecord.id);if(s)s.dueDate=next}
    hide('dateModal');hide('detailModal');await persist('일정 날짜를 변경했습니다.')}
  // 완료 취소 — 잘못 누른 `OK 완료` 를 되돌리는 경로. 기록·첨부·완료일 외 데이터는 그대로 둔다.
  async function reopenSelected(){if(!selectedRecord||!selectedRecord.completed)return;
    if(!confirm('완료를 취소하고 이 일정을 다시 진행 중으로 되돌릴까요?\n업무 기록과 첨부파일은 그대로 유지됩니다.'))return;
    const r=C.reopenEvent(state,selectedRecord);if(!r)return;hide('detailModal');
    await persist(r.kept?`완료를 취소했습니다. 다음 단계 ${r.kept.name}의 날짜(${C.pretty(r.kept.dueDate)})는 그대로 두었습니다.`:'완료를 취소했습니다.');}
  async function deleteSelected(){if(!selectedRecord||selectedRecord.kind!=='manual')return;
    const m=state.manualEvents.find(x=>x.id===selectedRecord.id);const files=C.attachmentIdsOf([m]);
    if(!confirm(files.length?`이 일정을 삭제할까요?\n첨부파일 ${files.length}개도 함께 삭제됩니다.`:'이 일정을 삭제할까요?'))return;
    state.manualEvents=state.manualEvents.filter(x=>x.id!==selectedRecord.id);
    await C.purgeAttachments(files); // 메타데이터만 지우면 IndexedDB 에 blob 이 영구히 남는다.
    hide('detailModal');await persist('일정을 삭제했습니다.')}
  function renderTemplatePanes(){renderVendorTemplates();renderWorkTemplates()}
  function renderVendorTemplates(){if(!selectedVendorTemplateId&&state.vendorTemplates[0])selectedVendorTemplateId=state.vendorTemplates[0].id;const v=state.vendorTemplates.find(x=>x.id===selectedVendorTemplateId)||state.vendorTemplates[0];$('vendorTemplatePane').innerHTML=`<div class="template-layout"><div><div class="template-list">${state.vendorTemplates.map(x=>`<button class="template-item ${v?.id===x.id?'active':''}" data-vt="${x.id}">${C.esc(x.name)}</button>`).join('')}</div><button class="btn" id="newVendorTemplate" style="margin-top:7px;width:100%">+ 업체 템플릿</button></div><div class="template-editor"><div class="editor-head"><div class="editor-title">업체 정보</div>${v?'<button class="btn danger" id="deleteVendorTemplate">삭제</button>':''}</div>${v?`<div class="form-grid"><div class="field full"><label>업체명</label><input id="vtName" value="${C.esc(v.name)}"></div><div class="field"><label>담당자</label><input id="vtPerson" value="${C.esc(v.person||'')}"></div><div class="field"><label>연락처</label><input id="vtContact" value="${C.esc(v.contact||'')}"></div><div class="field full"><label>메모</label><textarea id="vtMemo">${C.esc(v.memo||'')}</textarea></div></div><button class="btn primary" id="saveVendorTemplate" style="margin-top:8px">업체 저장</button>`:'업체 템플릿을 추가하세요.'}</div></div>`;qa('[data-vt]').forEach(b=>b.addEventListener('click',()=>{selectedVendorTemplateId=b.dataset.vt;renderVendorTemplates()}));q('#newVendorTemplate')?.addEventListener('click',()=>{const id=C.uid('v');state.vendorTemplates.push({id,name:'신규 업체',person:'',contact:'',memo:''});selectedVendorTemplateId=id;renderVendorTemplates()});q('#saveVendorTemplate')?.addEventListener('click',async()=>{Object.assign(v,{name:$('vtName').value.trim()||v.name,person:$('vtPerson').value.trim(),contact:$('vtContact').value.trim(),memo:$('vtMemo').value.trim()});await persist('업체 템플릿을 저장했습니다.')});q('#deleteVendorTemplate')?.addEventListener('click',async()=>{if(state.projects.some(p=>p.vendorId===v.id)||state.manualEvents.some(m=>m.vendorId===v.id)){toast('사용 중인 업체 템플릿은 삭제할 수 없습니다.');return}state.vendorTemplates=state.vendorTemplates.filter(x=>x.id!==v.id);selectedVendorTemplateId=state.vendorTemplates[0]?.id||null;await persist('업체 템플릿을 삭제했습니다.')})}
  function renderWorkTemplates(){if(!selectedWorkTemplateId&&state.workTemplates[0])selectedWorkTemplateId=state.workTemplates[0].id;const t=state.workTemplates.find(x=>x.id===selectedWorkTemplateId)||state.workTemplates[0];$('workTemplatePane').innerHTML=`<div class="template-layout"><div><div class="template-list">${state.workTemplates.map(x=>`<button class="template-item ${t?.id===x.id?'active':''}" data-wt="${x.id}">${C.esc(x.name)}</button>`).join('')}</div><button class="btn" id="newWorkTemplate" style="margin-top:7px;width:100%">+ 업무 템플릿</button></div><div class="template-editor"><div class="editor-head"><div class="editor-title">업무 절차</div>${t?'<button class="btn danger" id="deleteWorkTemplate">삭제</button>':''}</div>${t?`<div class="field full"><label>템플릿명</label><input id="wtName" value="${C.esc(t.name)}"></div><div class="proc-list" id="wtSteps" style="margin-top:8px"></div><button class="btn" id="wtAddStep" style="margin-top:7px">+ 단계 추가</button><button class="btn primary" id="saveWorkTemplate" style="margin-top:7px">템플릿 저장</button>`:'업무 템플릿을 추가하세요.'}</div></div>`;if(t)renderStepEditor('wtSteps',t.steps,()=>renderWorkTemplates());qa('[data-wt]').forEach(b=>b.addEventListener('click',()=>{selectedWorkTemplateId=b.dataset.wt;renderWorkTemplates()}));q('#newWorkTemplate')?.addEventListener('click',()=>{const id=C.uid('wt');state.workTemplates.push({id,name:'신규 업무 템플릿',steps:[{name:'첫 일정',offset:0}]});selectedWorkTemplateId=id;renderWorkTemplates()});q('#wtAddStep')?.addEventListener('click',()=>{t.steps.push({name:'새 단계',offset:1});renderWorkTemplates()});q('#saveWorkTemplate')?.addEventListener('click',async()=>{t.name=$('wtName').value.trim()||t.name;await persist('업무 템플릿을 저장했습니다.')});q('#deleteWorkTemplate')?.addEventListener('click',async()=>{state.workTemplates=state.workTemplates.filter(x=>x.id!==t.id);selectedWorkTemplateId=state.workTemplates[0]?.id||null;await persist('업무 템플릿을 삭제했습니다.')})}
  function renderStepEditor(hostId,steps,rerender){const host=$(hostId);host.innerHTML=steps.map((s,i)=>`<div class="proc-row"><div class="move"><button data-up="${i}">↑</button><button data-down="${i}">↓</button></div><input data-step-name="${i}" value="${C.esc(s.name)}"><input data-step-offset="${i}" type="number" min="0" value="${Number(s.offset||0)}" title="이전 단계 완료 후 일수"><button class="remove" data-remove="${i}">삭제</button></div>`).join('');qa('[data-step-name]',host).forEach(el=>el.addEventListener('input',()=>steps[+el.dataset.stepName].name=el.value));qa('[data-step-offset]',host).forEach(el=>el.addEventListener('input',()=>steps[+el.dataset.stepOffset].offset=Number(el.value||0)));qa('[data-up]',host).forEach(b=>b.addEventListener('click',()=>move(+b.dataset.up,-1)));qa('[data-down]',host).forEach(b=>b.addEventListener('click',()=>move(+b.dataset.down,1)));qa('[data-remove]',host).forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.remove,s=steps[i]||{};const lost=[];if(s.completed)lost.push(`완료 이력${s.completedAt?` (${C.pretty(s.completedAt)})`:''}`);if(s.logs?.length)lost.push(`업무 기록 ${s.logs.length}건`);if(s.attachments?.length)lost.push(`첨부파일 ${s.attachments.length}개`);if(lost.length&&!confirm(`'${s.name}' 단계를 삭제하면 다음이 함께 사라집니다.\n\n- ${lost.join('\n- ')}\n\n삭제할까요?`))return;steps.splice(i,1);rerender()}));function move(i,d){const j=i+d;if(j<0||j>=steps.length)return;[steps[i],steps[j]]=[steps[j],steps[i]];rerender()}}
  function openProjectSteps(projectId){selectedProjectId=projectId;const p=C.project(state,projectId);projectStepsDraft=C.clone(p.steps);$('projectStepsTitle').textContent=`${p.name} · 절차 편집`;renderProjectSteps();show('projectStepsModal')}
  function renderProjectSteps(){renderStepEditor('projectStepsList',projectStepsDraft,renderProjectSteps)}
  async function saveProjectSteps(){const p=C.project(state,selectedProjectId);if(!p)return;
    const kept=new Set(projectStepsDraft.map(s=>s.id).filter(Boolean)),dropped=p.steps.filter(s=>!kept.has(s.id));
    p.steps=projectStepsDraft.map(s=>({...s,id:s.id||C.uid(`${p.id}s`),offset:Number(s.offset||0)}));
    hide('projectStepsModal');
    if(dropped.length)await C.purgeAttachments(C.attachmentIdsOf(dropped));
    await persist('이 업무의 절차를 저장했습니다.')}
  function openTemplates(){templateTab='vendor';qa('[data-template-tab]').forEach(b=>b.classList.toggle('active',b.dataset.templateTab==='vendor'));$('vendorTemplatePane').classList.remove('hidden');$('workTemplatePane').classList.add('hidden');renderTemplatePanes();show('templateModal')}
  async function openHelper(){if(C.isTauri()){try{await window.__TAURI__.core.invoke('show_helper');toast('D-day 도우미를 열었습니다.');return}catch(e){console.warn(e)}}window.open('helper.html','dday-helper','width=330,height=430,resizable=yes')}
  async function openSettings(){const tauri=C.isTauri();$('alwaysOnTop').checked=!!state.settings.helperAlwaysOnTop;$('autostart').checked=!!state.settings.autostart;if(tauri){try{$('autostart').checked=await window.__TAURI__.core.invoke('is_autostart_enabled');state.settings.autostart=$('autostart').checked}catch(e){}}renderDemoRow();show('settingsModal')}
  function renderDemoRow(){const on=C.hasDemoData(state);$('demoToggleBtn').textContent=on?'예시 데이터 지우기':'예시 데이터 불러오기';$('demoToggleBtn').classList.toggle('danger',on)}
  // 예시 데이터는 demo- 접두 id 로만 식별한다. 사용자가 직접 만든 업무는 절대 건드리지 않는다.
  async function toggleDemo(){
    const isDemo=x=>String(x.id).startsWith('demo-');
    if(C.hasDemoData(state)){
      if(!confirm('예시 데이터를 지울까요?\n직접 등록한 업무·일정은 그대로 유지됩니다.'))return;
      const dropped=[...state.projects.filter(isDemo).flatMap(p=>p.steps),...state.manualEvents.filter(isDemo)];
      state.projects=state.projects.filter(p=>!isDemo(p));state.manualEvents=state.manualEvents.filter(m=>!isDemo(m));
      await C.purgeAttachments(C.attachmentIdsOf(dropped));
      renderDemoRow();await persist('예시 데이터를 지웠습니다.');
    }else{
      const d=C.demoData();state.projects.push(...d.projects);state.manualEvents.push(...d.manualEvents);
      renderDemoRow();await persist('예시 데이터를 불러왔습니다.');
    }
  }
  // 도우미 창에서 카드를 누르면 공유 상태에 대상이 적히고 본체가 열린다. 본체는 그 대상을 소비해 상세를 띄운다.
  async function consumePendingSelection(){const sel=state.pendingSelection;if(!sel||!sel.id)return;
    state.pendingSelection=null;await C.saveState(state);
    if(findRecord(sel.kind,sel.id))openRecord(sel.kind,sel.id);}
  async function setTop(){state.settings.helperAlwaysOnTop=$('alwaysOnTop').checked;await C.saveState(state);if(C.isTauri())try{await window.__TAURI__.core.invoke('set_helper_always_on_top',{enabled:state.settings.helperAlwaysOnTop})}catch(e){} }
  async function setAutostart(){const enabled=$('autostart').checked;state.settings.autostart=enabled;await C.saveState(state);if(C.isTauri())try{await window.__TAURI__.core.invoke('set_autostart',{enabled})}catch(e){toast('자동실행 설정을 적용하지 못했습니다.')}}
  $('horizonSelect').addEventListener('change',async e=>{state.settings.horizon=e.target.value;$('horizonCustom').classList.toggle('hidden',e.target.value!=='custom');await persist()});$('horizonCustom').addEventListener('change',async e=>{state.settings.customHorizon=Math.max(1,Number(e.target.value||1));await persist()});
  $('prevMonth').addEventListener('click',()=>{currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()-1,1);renderCalendar()});$('nextMonth').addEventListener('click',()=>{currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+1,1);renderCalendar()});$('todayBtn').addEventListener('click',()=>{const d=C.parse(C.todayISO());currentMonth=new Date(d.getFullYear(),d.getMonth(),1);renderCalendar();setTimeout(()=>q('.day.today')?.scrollIntoView({block:'center',behavior:'smooth'}),10)});
  $('addScheduleBtn').addEventListener('click',()=>openSchedule());$('saveScheduleBtn').addEventListener('click',saveSchedule);$('sVendor').addEventListener('change',updateProjectSelect);$('addWorkBtn').addEventListener('click',openWork);$('saveWorkBtn').addEventListener('click',saveWork);$('templateBtn').addEventListener('click',openTemplates);$('settingsBtn').addEventListener('click',openSettings);$('helperBtn').addEventListener('click',openHelper);$('settingsOpenHelper').addEventListener('click',openHelper);$('alwaysOnTop').addEventListener('change',setTop);$('autostart').addEventListener('change',setAutostart);$('completeBtn').addEventListener('click',completeSelected);$('changeDateBtn').addEventListener('click',openDateModal);$('saveDateBtn').addEventListener('click',saveSelectedDate);$('reopenBtn').addEventListener('click',reopenSelected);$('deleteEventBtn').addEventListener('click',deleteSelected);$('demoToggleBtn').addEventListener('click',toggleDemo);$('projectAddStep').addEventListener('click',()=>{projectStepsDraft.push({id:null,name:'새 단계',offset:1,dueDate:null,completed:false,completedAt:null});renderProjectSteps()});$('saveProjectSteps').addEventListener('click',saveProjectSteps);
  qa('[data-template-tab]').forEach(b=>b.addEventListener('click',()=>{templateTab=b.dataset.templateTab;qa('[data-template-tab]').forEach(x=>x.classList.toggle('active',x===b));$('vendorTemplatePane').classList.toggle('hidden',templateTab!=='vendor');$('workTemplatePane').classList.toggle('hidden',templateTab!=='work')}));qa('[data-close]').forEach(b=>b.addEventListener('click',()=>hide(b.dataset.close)));qa('.modal-bg').forEach(bg=>bg.addEventListener('mousedown',e=>{if(e.target===bg)hide(bg.id)}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=qa('.modal-bg.show').pop();if(open)hide(open.id)}});
  await C.watchState(v=>{state=v;render();consumePendingSelection()});
  const d=C.parse(C.todayISO());currentMonth=new Date(d.getFullYear(),d.getMonth(),1);render();consumePendingSelection();setTimeout(()=>q('.day.today')?.scrollIntoView({block:'center'}),50);
})();
