import { chromium } from "@playwright/test";
const OUT = "/tmp/claude-0/-home-user-WorkDashboard/ece9e0f3-3cba-5d14-bf87-08720ba9d603/scratchpad/shots";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell" });
const errors = [];
async function run(scheme) {
  const ctx = await browser.newContext({ viewport: { width: 1366, height: 768 }, locale: "ko-KR", timezoneId: "Asia/Seoul", colorScheme: scheme });
  const page = await ctx.newPage();
  page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") errors.push(`[${scheme}] ${m.type()}: ${m.text().slice(0, 300)}`); });
  page.on("pageerror", (e) => errors.push(`[${scheme}] pageerror: ${e.message}`));
  await page.goto("http://127.0.0.1:4173/");
  await page.waitForSelector('[data-testid="widget"]');
  const shot = async (n) => { await page.waitForTimeout(300); await page.screenshot({ path: `${OUT}/${scheme}-${n}.png` }); };
  await shot("00-widget");
  await page.getByTestId("widget").click();
  await page.waitForSelector('[data-testid="layer1"]');
  await shot("01-today");
  await page.getByTestId("open-calendar").click();
  await page.waitForSelector('[data-testid="layer2"]');
  await shot("02-matrix");
  await page.getByRole("tab", { name: "월간" }).click();
  await page.waitForSelector('[data-testid="month"]');
  await shot("03-month");
  await page.getByRole("tab", { name: "주간" }).click();
  await page.waitForSelector('[data-testid="week"]');
  await shot("04-week");
  await page.getByRole("tab", { name: "기간표" }).click();
  await page.waitForSelector('[data-testid="matrix"]');
  await page.getByTestId("vendor-V01").click();
  await page.waitForSelector('[data-testid="inspector-vendor"]');
  await shot("05-inspector-vendor");
  await page.getByTestId("cell-P01-2026-09-12").click();
  await page.waitForSelector('[data-testid="de-save"]');
  await shot("06-day-exception");
  await page.keyboard.press("Escape");
  await page.waitForSelector('[data-testid="de-save"]', { state: "detached" });
  await page.getByTestId("plan-edit-P01").click();
  await page.waitForSelector('[data-testid="pe-save"]');
  await page.getByTestId("pe-wd-1").click();
  await shot("07-plan-edit");
  await page.keyboard.press("Escape");
  await page.keyboard.press("Control+n");
  await page.waitForSelector('[data-testid="qa-title"]');
  await page.getByTestId("qa-title").fill("군수 보고 자료 인쇄");
  await shot("08-quick-add");
  await page.keyboard.press("Escape");
  await page.getByTestId("add-vendor").click().catch(() => page.getByText("업체 등록", { exact: true }).first().click());
  await page.waitForSelector('[data-testid="vr-save"]');
  await page.getByTestId("vr-name").fill("고성수산");
  await page.getByTestId("vr-wd-6").click();
  await shot("09-vendor-register");
  await page.keyboard.press("Escape");
  await (page.getByTestId("open-restore").click().catch(() => page.getByText("보관본에서 복원", { exact: true }).first().click()));
  await page.waitForSelector('[data-testid="rs-run"]');
  await page.getByTestId("rs-B2").click();
  await page.waitForTimeout(600);
  await shot("10-restore");
  await page.keyboard.press("Escape");
  // E3 연말 event (year boundary), and empty event? select E3
  await page.getByTestId("event-E3").click();
  await page.waitForTimeout(200);
  await shot("11-matrix-E3");
  await page.getByTestId("event-E1").click();
  await page.addStyleTag({ content: "html{filter:grayscale(1)}" });
  await shot("12-matrix-grayscale");
  await ctx.close();
}
try { await run("light"); await run("dark"); } catch (e) { console.log("FAILED:", e.message.split("\n")[0]); const pg = browser.contexts()[0]?.pages()[0]; if (pg) await pg.screenshot({ path: `${OUT}/failed.png` }); } finally { await browser.close(); }
console.log(errors.length ? errors.join("\n") : "console: no errors/warnings");
